<?php

return array(
    'Andorra',
    'Argentina',
    'Australia',
    'Austria',
    'Belarus',
    'Belgium',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Burma',
    'Canada',
    'Chile',
    'China',
    'China Taiwan',
    'Colombia',
    'Crotia',
    'Cuba',
    'Cyprus',
    'Czech Republic',
    'Denmark',
    'Ecuador',
    'Egypt',
    'Fiji Islands',
    'Finland',
    'France',
    'Germany',
    'Greece',
    'HK',
    'Hungary',
    'Iceland',
    'Iceland',
    'India',
    'Indonesia',
    'Indonesia',
    'Iran',
    'Ireland',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Korea',
    'Kyrgyzstan',
    'Liechtenstein',
    'Luxembourg',
    'Madagascar',
    'Malaysia',
    'Maldives',
    'Mexico',
    'Monaco',
    'Mongolia',
    'Morocco',
    'Netherlands',
    'New Zealand',
    'North Korea',
    'Norway',
    'Pacific Ocean',
    'Pakistan',
    'Peru',
    'Philippines',
    'Poland',
    'PORTUGAL',
    'Puerto Rico',
    'Qatar',
    'Romania',
    'Russia',
    'Saudi Arab',
    'Scotland',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'South Africa',
    'Spain',
    'Sri Lanka',
    'Sweden',
    'Switzerland',
    'Syria',
    'Thailand',
    'The Republic of Mauritius',
    'The State of Israel',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'UAE',
    'Ukraine',
    'United Kingdom',
    'United States',
    'Uruguay',
    'Uzbekistan',
    'Vatican',
    'Vietnam',
    'Yemen',
)


?>